### ISSUE TITLE
Using tf.app.flags instead of argparse

### ISSUE THREAD

**Issue by nakosung** [ibab/tensorflow-wavenet#138]
Isn't it much more natural for tensorflow project?

**Comment by ibab** [comment]
I like the extra flexibility of using argparse directly.
TensorFlow uses argparse internally to implement `tf.apps.flags`: http://stackoverflow.com/questions/33932901/whats-the-purpose-of-tf-app-flags-in-tensorflow

**Comment by nakosung** [comment]
Okay. I think it would be great because I used to do with gflags in c++. :) Closing this issue.

**Comment by lemonzi** [comment]
Not only that, but tensorflow recommends against it - it's an unofficial,
unsupported, internal wrapper needed for compatibility with the Google
infrastructure, but it could change any time.

On Mon, Oct 10, 2016, 08:58 Nako Sung <notifications@github.com> wrote:

Closed #138 <https://github.com/ibab/tensorflow-wavenet/issues/138>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ibab/tensorflow-wavenet/issues/138#event-817975654>,
or mute
the thread
