### ISSUE TITLE
Can this project support other language?

### ISSUE THREAD

**Issue by EdwardBX** [ibab/tensorflow-wavenet#148]
Hi, I really love your project.
Here is a small question: Can this project support other language? For example, Chinese.
Looking for your reply.

**Comment by lemonzi** [comment]
The model is generic and works for any audio input (including music and other languages) -- some people are even using it for other modalities, such as text and images. The only difficulty is in the data input: the current code reads from the VCTK dataset. However, since we don't have local or global conditioning yet, you can train it on other datasets by supplying a folder contaning the audio files that you want to use as `--data_dir`.

**Comment by lemonzi** [comment]
So, if you have the chinese audio files in `~/Data/Audio`, you would run `python ./train.py --silence_threshold 0 --data_dir ~/Data/Audio`. I'd suggest setting the threshold to 0 with new datasets, so that you make sure it doesn't trim too much and you don't get weird results.

**Comment by EdwardBX** [comment]
@lemonzi  It's worth a try, thank you so much.
