### ISSUE TITLE
librosa.util.exceptions.ParameterError: Buffer is too short (n=1427) for frame_length=2048

### ISSUE THREAD

**Issue by Jovonni** [ibab/tensorflow-wavenet#228]
Exception in thread Thread-13:
Traceback (most recent call last):
  File "//anaconda/envs/py35/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "//anaconda/envs/py35/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/fs8b/Documents/tech/tensorflow-wavenet-master/wavenet/audio_reader.py", line 162, in thread_main
    audio = trim_silence(audio[:, 0], self.silence_threshold)
  File "/Users/fs8b/Documents/tech/tensorflow-wavenet-master/wavenet/audio_reader.py", line 66, in trim_silence
    energy = librosa.feature.rmse(audio)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/librosa/feature/spectral.py", line 575, in rmse
    hop_length=hop_length)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/librosa/util/utils.py", line 82, in frame
    ' for frame_length={:d}'.format(len(y), frame_length))
librosa.util.exceptions.ParameterError: Buffer is too short (n=1427) for frame_length=2048

After training on the entire VCTK-Corpus, this is the error of which kills execution. Has anybody else encountered this?

Still cannot even train successfully, let alone generate audio

**Comment by goldlhz** [comment]
I have this problem too

**Comment by lemonzi** [comment]
Does it only happen on TensorFlow 1.0.0? It could be that one of the API's used during padding has changed.

**Comment by dbl001** [comment]
I also have it.
I'm running: '1.0.1'

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/davidlaxer/anaconda/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/davidlaxer/tensorflow-wavenet/wavenet/audio_reader.py", line 162, in thread_main
    audio = trim_silence(audio[:, 0], self.silence_threshold)
  File "/Users/davidlaxer/tensorflow-wavenet/wavenet/audio_reader.py", line 66, in trim_silence
    energy = librosa.feature.rmse(audio)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/librosa/feature/spectral.py", line 575, in rmse
    hop_length=hop_length)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/librosa/util/utils.py", line 82, in frame
    ' for frame_length={:d}'.format(len(y), frame_length))
ParameterError: Buffer is too short (n=1388) for frame_length=2048

**Comment by lemonzi** [comment]
The only thing I can think of is that one of the audio files is extremely short. Can someone with the issue wrap https://github.com/ibab/tensorflow-wavenet/blob/master/wavenet/audio_reader.py#L162 in a try..except block, print the filename when the exception is thrown, and check if there's something wrong with the file?

We should add a check that skips files that are too short and emits a warning.

**Comment by dbl001** [comment]
Is it training after this exception?  It's getting CPU time:

501 81160  2640   0 12:19PM ttys012   **11:17.52** python train.py --data_dir=/Users/davidlaxer/Downloads/VCTK-Corpus/wav48

501 81160  2640   0 12:19PM ttys012   **11:22.21** python train.py --data_dir=/Users/davidlaxer/Downloads/VCTK-Corpus/wav48

501 81160  2640   0 12:19PM ttys012   **11:23.63** python train.py --data_dir=/Users/davidlaxer/Downloads/VCTK-Corpus/wav48

**Comment by lemonzi** [comment]
Since the exception happens in one of the queue threads, it could be that the others continue training unless `stop_on_exception()` and `should_stop()` from the Coordinator are used.

**Comment by dbl001** [comment]
CTRL C doesn't do anything.  Should I kill the process, remove the small file audio and try again?

**Comment by lemonzi** [comment]
@dbl001 Hmm the interrupt is probably getting intercepted. I very often have to kill Python when running TF. Did you find the file then?

**Comment by dbl001** [comment]
Any of these look ‘too small’?

102 KB	./p351/p351_361.wav
87 KB	./p363/p363_354.wav
82 KB	./p306/p306_151.wav
81 KB	./p361/p361_173.wav
57 KB	./p323/p323_424.wav
49 KB	./p295/p295_334.wav
41 KB	./p335/p335_424.wav
28 KB	./p305/p305_423.wav
16 KB	./p295/p295_047.wav
8 KB	./p345/p345_387.wav
8 KB	./p317/p317_424.wav

**Comment by lemonzi** [comment]
It complains the buffer was only 1427 samples long, which should be around 3 KB assuming mono files at 16 kHz. But with the disk block size (I don't really know how it works) it could be the 8 KB files.

**Comment by dbl001** [comment]
I removed both 8k files, then tried to retrain.

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/davidlaxer/anaconda/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/davidlaxer/tensorflow-wavenet/wavenet/audio_reader.py", line 162, in thread_main
    audio = trim_silence(audio[:, 0], self.silence_threshold)
  File "/Users/davidlaxer/tensorflow-wavenet/wavenet/audio_reader.py", line 66, in trim_silence
    energy = librosa.feature.rmse(audio)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/librosa/feature/spectral.py", line 575, in rmse
    hop_length=hop_length)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/librosa/util/utils.py", line 82, in frame
    ' for frame_length={:d}'.format(len(y), frame_length))
ParameterError: Buffer is too short (n=1427) for frame_length=2048

**Comment by dbl001** [comment]
How can I get tensorflow to utilize all my cores:

python train.py --data_dir=/Users/davidlaxer/Downloads/VCTK-Corpus/wav48

E.g. 

sess = tf.Session(config=tf.ConfigProto(
  intra_op_parallelism_threads=NUM_THREADS))
 <http://stackoverflow.com/a/39395608/4851368>

?

**Comment by lemonzi** [comment]
@dbl001 About the buffer error: Well, that's weird. It could also be that one of the reshapes is incorrect, but then nothing would work. I guess we can always skip silence trimming (which is what's causing the error) if the audio vector is shorter than 2048.

About the cores: you shouldn't need to specify it in the ConfigProto. AFAIK, by default it will use all cores; you only need to tweak that if you need more control (say, you only want to use a fraction of them because you are running models in parallel). Is it always using a single core, or just not using all of them? 
In this implementation, there are three sources of parallelism: the operations (matrix multiplies, etc) themselves being implemented multi-core, which is that intra-op parallelism, different ops that are run in a single sess.run() call and are independent also run in parallel (inter-op parallelism), and finally there are threads that read audio files in feed them to the Queue in parallel to the training itself.
One limitation that running TensorFlow in a single process has is that it only works in multi-core while session.run() is being called, because of the global lock in Python. All control logic will be single-threaded. Since reading from disk is not locked by the Python lock though, adding threads that read to the Queue really helps in avoiding those I/O waits. 
If you train on CPU, most of the actual multi-core utilization will come from intra-op parallelism, which is fully exploited when you have a large batch size, because the matrices become larger. In this implementation, the batch size is set to 1 audio file. Internally, however, batches are created by splitting the audio file in chunks, so the longer the audio file is the larger the effective batch size will be.
If you get poor utilization (especially if you have a lot of cores), it could be the audio files are a bit short. One of the to-do's is to allow the batch size to be greater than 1, which would take care of this. 
If you run on GPU and you have a big CPU, provided you have a decent input pipeline with Queues and threads and all, it's usually the GPU itself the limiting factor.
Another way to get more parallelism if you train on CPU is to run TensorFlow in distributed mode creating a local cluster, in which case the Python lock is no longer a limiting factor. This would require some code changes, though. You would have several copies of the model running in parallel in different processes, reading and writing the model weights to a "master" process (the parameter sever). If you train on a single GPU, this wouldn't help much because GPU's don't multi-task well.

**Comment by dbl001** [comment]
I’m currently running  Ubuntu 14.04 LTS on a 16 core EC2 m4.4xlarge instance

m4.4xlarge	16	cpu 64 gigabytes

Here’s stop output.
Most of the cores are unused.  Suggestions?

**Comment by lemonzi** [comment]
The instance you are using has network-attached storage only, which means loading the audio files will be much slower than usual. What probably happens is that they are not loaded quickly enough into the queue and the CPU just sits there waiting for data. By default, only 1 thread reads data from disk, you can increase that in `train.py`, line 290 (https://github.com/ibab/tensorflow-wavenet/blob/master/train.py#L290) like this:

```python
reader.start_threads(sess, num_threads=NUM_THREADS)
```

Set num_threads to the number of concurrent network requests to the EBS you want to have. You may also have to tweak the queue size in the line 218, where the `AudioReader` is created, by adding the argument `queue_size=QUEUE_SIZE`. Tweaking these two parameters may take some trial and error.

Another thing to consider is using a GPU instance, which will probably train faster overall. p2.xlarge and g2.2xlarge have similar pricing.

Generation will be a bit slow no matter what, because of both the model itself and its implementation.

**Comment by dbl001** [comment]
Ok.  I’ll try a GPU instance.
Have you tried TensorFlowOnSpark (compliments Yahoo)?

**Comment by lemonzi** [comment]
No, I've always used the "regular" tensorflow... (both locally and distributed). To be clear: the GPU will help, but if you have slow I/O (and even regular hard drives could be "slow" here) you definitely need to increase the number of threads that read data.

**Comment by dbl001** [comment]
I’m still getting the error on the Mac.  Any ideas?

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/davidlaxer/anaconda/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/davidlaxer/tensorflow-wavenet/wavenet/audio_reader.py", line 162, in thread_main
    audio = trim_silence(audio[:, 0], self.silence_threshold)
  File "/Users/davidlaxer/tensorflow-wavenet/wavenet/audio_reader.py", line 66, in trim_silence
    energy = librosa.feature.rmse(audio)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/librosa/feature/spectral.py", line 575, in rmse
    hop_length=hop_length)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/librosa/util/utils.py", line 82, in frame
    ' for frame_length={:d}'.format(len(y), frame_length))
ParameterError: Buffer is too short (n=1427) for frame_length=2048

**Comment by ChristofHenkel** [comment]
I think of 3 solutions:

a) change librosas frame_length:
audio_reader.py line 66: `energy = librosa.feature.rmse(audio, frame_length = 1024)`
However then you still get the error with files smaller than 1024

b) skip energy of small files:
`if audio.size < 2048:`
`energy` = 0`
`else:`
` energy = librosa.feature.rmse(audio)`

c) ignore small files in general

**Comment by dbl001** [comment]
It’s training with this change.
>  66: energy = librosa.feature.rmse(audio, frame_length = 1024)
> 
> 


Should I see Audio files in TesorBords Audio tab?

$ tensorboard --logdir logdir/train/
Starting TensorBoard 41 on port 6006
(You can navigate to http://192.168.1.5:6006)

**Comment by lemonzi** [comment]
I think the best solution would be to not trim silence from small files, it doesn't make sense anyway. @dbl001, IIRC there are no audio summaries -- once you have the model trained, the generation script directly creates a wav file when you run it.

**Comment by dbl001** [comment]
I’m training WaveNet on an AWS EC2 g2.2xlarge spot instance.
I set —logdir_root to be a EBS volume whose be preserved if/when the instance is preempted.
I left the checkpoint at the default.

If the instance is preempted and I restart the training, will TensorFlow pickup from the last checkpoint?

**Comment by lemonzi** [comment]
@dbl001 If you want the training to resume you should use `logdir`, not `logdir_root`. `logdir_root` will create a folder with the current date and time with the model every time you run the script, while `logdir` will load whatever it finds at the folder you give it and continue training. You can also "fork" by loading a saved model and saving future iterations to another folder using `restore_from`.
